on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - v*

name: Rust

env:
  CARGO_TERM_COLOR: always

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run --profile=ci --all-features
      - name: Run doctests
        run: cargo test --doc
      - name: Upload test results
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: target/nextest/ci/junit.xml
          check_name: "Test Runs: ${{ matrix.os }}"
          comment: ${{ github.event_name == 'pull_request' }}
          include_passed: true
          include_time_in_summary: true
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref_type == 'tag' && github.repository == 'der-fruhling/rocket-identity'

    steps:
      - uses: actions/checkout@v6
      - name: Publish crate
        run: cargo publish
        env:
          CARGE_REGISTRY_TOKEN: ${{ secrets.cargo-api-token }}
