on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - v*

name: Rust

env:
  CARGO_TERM_COLOR: always

permissions:
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@nextest
      - name: Create recording user config
        shell: bash
        run: |
          mkdir -p "$RUNNER_TEMP/nextest-config"
          printf '[experimental]\nrecord = true\n\n[record]\nenabled = true\n' \
            > "$RUNNER_TEMP/nextest-config/config.toml"
          cat "$RUNNER_TEMP/nextest-config/config.toml"
      - name: Build
        id: build
        run: cargo build --workspace --all --all-features
      - name: Run tests
        if: steps.build.conclusion == 'success' && !cancelled()
        run: cargo nextest run --profile=ci --all-features --user-config-file "$RUNNER_TEMP/nextest-config/config.toml"
        env:
          NEXTEST_EXPERIMENTAL_RECORD: 1
      - name: Create portable archive from recorded run
        # Run this step even if the test step fails.
        if: steps.build.conclusion == 'success' && !cancelled()
        shell: bash
        run: |
          cargo nextest store export latest \
            --user-config-file "$RUNNER_TEMP/nextest-config/config.toml" \
            --archive-file "$RUNNER_TEMP/nextest-run-${{ matrix.os }}.zip"
      - name: Upload recording
        if: steps.build.conclusion == 'success' && !cancelled()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ runner.temp }}/nextest-run-${{ matrix.os }}.zip
          archive: false
      - name: Run doctests
        if: steps.build.conclusion == 'success' && !cancelled()
        run: cargo test --doc
      - name: Upload test results
        uses: mikepenz/action-junit-report@v6
        if: steps.build.conclusion == 'success' && !cancelled()
        with:
          report_paths: target/nextest/ci/junit.xml
          check_name: "Test Runs: ${{ matrix.os }}"
          comment: ${{ github.event_name == 'pull_request' }}
          include_passed: true
          include_time_in_summary: true
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref_type == 'tag' && github.repository == 'der-fruhling/rocket-identity'

    steps:
      - uses: actions/checkout@v6
      - name: Publish crate
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.cargo_api_token }}
